server:
  port: 8080
spring:
  application:
    name: HAIBAZO_EntranceTest
  datasource:
    url: jdbc:mysql://localhost:3306/HaibazoEntranceTest?createDatabaseIfNotExist=true
    username: root
    password: 17062003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true