server:
  port: 8080
spring:
  application:
    name: HAIBAZO_EntranceTest
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haibazo_entrance_test?createDatabaseIfNotExist=true
    username: root
    password: 17062003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true